services:
  minio:
    image: minio/minio:latest
    container_name: s3
    ports:
      - "9000:9000"
    expose:
      - "9001"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    env_file:
      - .env
    command: server /data --console-address ":9001"
    networks:
      - traefik_network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

volumes:
  minio_data:
    driver: local
  minio_config:
    driver: local

networks:
  traefik_network:
    external: true
